function a1_0xaf9d() {
    const _0x44cecb = [
        'DisplayNames',
        'function',
        'fromCodePoint',
        'WINDOW',
        'brands',
        'model',
        'RelativeTimeFormat',
        '48DttPaQ',
        'start',
        'warn',
        'push',
        'UNMASKED_RENDERER_WEBGL',
        '(((.+)+)+)+$',
        'ReportingObserver',
        '8iScQsY',
        'error',
        'value',
        'userAgentData',
        'currency',
        'done',
        'now',
        'exception',
        'search',
        'getMonth',
        '{}.constructor("return this")( )',
        'toLocaleString',
        '1207989AYvnuK',
        'navigator',
        '8741612lxMbKO',
        'OTHER',
        'ListFormat',
        '7591600zpsSsP',
        'LINUX',
        'filter',
        'location',
        'keyboard',
        '49xKYWDv',
        'mobile',
        'WORKER',
        'toString',
        'Collator',
        'getHighEntropyValues',
        'bind',
        'uaFullVersion',
        'ports',
        'bitness',
        '815946FVxkin',
        'getContext',
        'resolvedOptions',
        '__proto__',
        'reduce',
        'NumberFormat',
        'length',
        'connect',
        'APPLE',
        'return (function() ',
        'source',
        '2008GFhMki',
        'parse',
        'brandsVersion',
        'proxy behavior detected',
        'stop',
        'match',
        'DateTimeFormat',
        'info',
        'Windows',
        'split',
        'flat',
        '24FkTBwQ',
        'platform',
        'PluralRules',
        'postMessage',
        '556184bKvOvq',
        'prototype',
        'constructor',
        'catch',
        'trace',
        '1675ZxzQOm',
        'version',
        'console',
        'getDate',
        'then',
        'Other',
        'keys',
        'sort',
        'join',
        'getParameter',
        'apply',
        'WINDOWS',
        'message',
        'throw',
        'brand',
        'test',
        'next',
        'ServiceWorkerGlobalScope',
        'platformVersion',
        'document',
        'webgl',
        '571416GOdsZs',
        'WEBGL_debug_renderer_info',
        'table',
        'name',
        'getExtension',
        'USD',
        'toFixed'
    ];
    return _0x44cecb;
}

function a1_0x830c(_0x26cdd3, _0x1dedbf) {
    const _0x2fa651 = a1_0xaf9d();
    return a1_0x830c = function (_0x564f5d, _0xaf9df2) {
        _0x564f5d = _0x564f5d - (7501 + -6684 + -339);
        let _0x830ca6 = _0x2fa651[_0x564f5d];
        return _0x830ca6;
    }, a1_0x830c(_0x26cdd3, _0x1dedbf);
}

function _0x162aad(_0x3dcec5, _0x121d2d) {
    return a1_0x830c(_0x3dcec5 - 364, _0x121d2d);
}

console.log(1505347 + 70129 * -11)
